### ISSUE TITLE
Обновить моды хD

### ISSUE THREAD

**Issue by ExpertLove** [FactorioParanoidal/ParanoidalModpack#116]
Аккуратно, сравнивая папки модов через Araxis Merge к примеру

**Comment by SKProCH** [comment]
> сравнивая папки модов через Araxis Merge
Достаточно смотреть в любой GIT GUI и смотреть что изменилось перед тем, как коммитить

**Comment by ExpertLove** [comment]
Просмотрел практически все моды.
Боб ангел без изменений/
Остальные контент моды тоже

Имеет смысл обновить только Rampant_fixed и Big_monsters
И то, ничего особенного там не появилось

ЛУчше ничего не обновлять
