### ISSUE TITLE
Сломана дальность подбора предметов в RPG

### ISSUE THREAD

**Issue by raptorggi** [FactorioParanoidal/ParanoidalModpack#140]
```
sapphire
что как?
просто нажимаю на f а ресурсы собираются с каких то далеких конвееров и заполняют весь инвентарь полностью
посмотрел на название про RPG и убрал галочку в рпг - системе
```
https://discord.com/channels/569536773701500928/585840620862439425/1280841939846959157
Возможно этот коммит ломает
https://github.com/FactorioParanoidal/ParanoidalModpack/commit/76b8ac2da0b0d603c1206c7ff8fa66eab0a8e3e1

**Comment by ExpertLove** [comment]
Все правильно, Дальность подбора при установки галочки в рпг = 20 клеток
Специально для удобного подбора мусора после кусак
Если убрать её- становится стандартной.
Она по дефоолту была включена?

**Comment by raptorggi** [comment]
Это неочевидное поведение для RPG мода. Нигде об этом нет описания и должно быть вынесено куда-то отдельно,  может в отдельную кнопку.

**Comment by ExpertLove** [comment]
Это и так вынесено в отдельную кнопку , точнее говоря пока галочка активна
По дефолту она выключена, пока юзер не нажмёт не заработает

Возможно надо описание для этой фичи подправить, позже гляну

**Comment by ExpertLove** [comment]
fixed #141
