### ISSUE TITLE
Доработка UED-Underground Energy distribution

### ISSUE THREAD

**Issue by RogeVenham** [FactorioParanoidal/ParanoidalModpack#166]
Предлагаю добавить несколько тиров аналогично столбам и подстанциям.
В текущем состоянии есть только 7x7 9 и 4x4 30 + урезанный аналог подстанции 15x15 18 против 18x18 18 у подстанции 1го тира.

**Comment by SKProCH** [comment]
Это было сознательное урезание, что бы подземные источники имели минусы относительно своих наземных вариантов.

**Comment by RogeVenham** [comment]
Урезание получается только в подстанции? Или отсутствие тиров тоже урезание?
Оффтоп вопросик: почему ЛЭП(7x7 9) первого тира требуется просто медь для крафта, хотя тому же ЛЭП(4x4 30) требуются провода, как и всем остальным тирам ЛЭП?

**Comment by SKProCH** [comment]
> Урезание получается только в подстанции?

Да

> Или отсутствие тиров тоже урезание?

Тоже да. Так как они не требуют места, то для покрытия любой области их просто нужно ставить чаще. Это хоть в какой-то мере компенсирует их преимущество перед обычными подстанциями и столбами, т.к. столбы можно погрейдить.

Изначально мы не вводили тиры, т.к. даже в текущем состоянии это слишком удобная штука. Т.е. в теории можно бы и тиры добавить, но как это адекватно балансить - пока не понятно, учитывая, что и сейчас оно слишком хорошо.

> Оффтоп вопросик: почему ЛЭП(7x7 9) первого тира требуется просто медь для крафта, хотя тому же ЛЭП(4x4 30) требуются провода, как и всем остальным тирам ЛЭП?

Вопрос хороший, наверное просто недосмотрели

**Comment by RogeVenham** [comment]
Спасибо за разъяснение
