### ISSUE TITLE
Обновить значение по умолчанию "show-pollution-visuals"

### ISSUE THREAD

**Issue by artemabogomolov** [FactorioParanoidal/ParanoidalModpack#168]
Версия 2.0.7, серверное исполнение.
Ошибка в логе: 
   0.255 Error Util.cpp:81: Error while loading mod-setting prototype "show-pollution-visuals" (bool-setting): Value must be a bool in property tree at ROOT.bool-setting.show-pollution-visuals.default_value
Modifications: pollution visuals › Picker Tweaks

Мод Picker Tweaks

Выполняемая команда: 
	data:extend({{
		type = "bool-setting",
		name = "show-pollution-visuals",
		default_value = "true",
		setting_type = "runtime-per-user",
	}})

**Comment by bogomolov-a-a** [comment]
Щас вас все эти игнорирования  всех этих типов будут бить по рукам, тут сотня таких ишью щас будет
