### ISSUE TITLE
what is the name of the modification?

### ISSUE THREAD

**Issue by Glocky077** [FactorioParanoidal/ParanoidalModpack#173]
who can tell you what the name of the mod is, which allows you to navigate through the appearance of the building and it will be built without pressing the LMB, if anyone understands, maybe he will tell you, I will be grateful

**Comment by SKProCH** [comment]
Did you mean factories from factorissimo? If yes, so its a feature of a factorissimo itself

**Comment by Glocky077** [comment]
> Вы имели в виду фабрики из Factorissimo? Если да, то это особенность самого Factorissimo

No, I'm talking about the "Picker Atheneum" modification, it has not been updated to the Factorio 2.0 version officially on the factorio modifications website, but in the discussion someone updated this mod officially for Factorio 2.0 and now it works

**Comment by SKProCH** [comment]
А, appearence это имеется в виду призрак, писал бы сразу на русском, че уж.  
Нет, я не знаю, обновлял ли кто-то picker моды под 2.0 и где это можно найти.

**Comment by Glocky077** [comment]
> А, «appearance» — это «призрак», надо было сразу писать по-русски. Нет, я не знаю, обновлял ли кто-нибудь моды для 2.0 и где их можно найти.

да я уже нашел под 2.0, а то что на английском, это же github, мало кто тут будет на русском писать и понимать я так думаю.

**Comment by SKProCH** [comment]
Зависит от комьюнити, у нас почти все в репе на русском
