### ISSUE TITLE
"Военная промышленность 3" недоступна для изучения

### ISSUE THREAD

**Issue by SKProCH** [FactorioParanoidal/ParanoidalModpack#18]
Не смотря на то, что все предшествующие технологии изучены

**Comment by SKProCH** [comment]
Судя по всему эти технологии не изучены, хотя отображаются изученными:

![image](https://github.com/FactorioParanoidal/ParanoidalModpack/assets/29896317/166078b0-6bf2-41aa-933c-a7faad2b0f16)

**Comment by ProTriforcer** [comment]
>Судя по всему эти технологии не изучены, хотя отображаются изученными

А они вообще не отображаются, кроме военки. Скрыты похоже.

**Comment by AKMFrtx** [comment]
я изучил без проблем. (сборка начала декабря 2023)

**Comment by artemabogomolov** [comment]
да надо просто применять мод на эти проверки технологического дерева на предмет скрытых(выключенных) технологий в предусловиях текущей. Иначе это будет треш. И сбрасывать прогресс технологий, если есть дыры, в том числе и скрытые(чего надо не допускать) в технологическом дереве этой технологии конкретной. Иначе это будет потом неиграбельно.

**Comment by artemabogomolov** [comment]
[2024-03-06.log](https://github.com/FactorioParanoidal/ParanoidalModpack/files/14514832/2024-03-06.log)
вывод мода check-technology-tree-mods-protocol c automated-fabrique-protocol и master

**Comment by AKMFrtx** [comment]
> Судя по всему эти технологии не изучены, хотя отображаются изученными:
> 
> ![image](https://private-user-images.githubusercontent.com/29896317/303778499-166078b0-6bf2-41aa-933c-a7faad2b0f16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NzU2ODAsIm5iZiI6MTcwOTk3NTM4MCwicGF0aCI6Ii8yOTg5NjMxNy8zMDM3Nzg0OTktMTY2MDc4YjAtNmJmMi00MWFhLTkzM2MtYTdmYWFkMmIwZjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDA5MDk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMTQ0MGYxZmFlZGRjZjcwOTMyNTcyNGEzNmJlOTAyYjM4NDY0YzgwMzg4MGI3YTg5OTM4NTA1N2ZlZWFhYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZDik5jU6kG7xGvELHbbvL0UHQmt-s7CipCKt2mMe0Zk)

а как узнать какие техи не изучены в таком случае?

**Comment by artemabogomolov** [comment]
вывести список зависимостей
