### ISSUE TITLE
8й версии нет насоса на старте

### ISSUE THREAD

**Issue by mrFANRA** [FactorioParanoidal/ParanoidalModpack#82]
8й версии нет насоса на старте. Это баг или фича?

**Comment by ExpertLove** [comment]
Твердотопливный лежит в обломках корабля

**Comment by ExpertLove** [comment]
> 8й версии нет насоса на старте. Это баг или фича?

Твердотопливный лежит в обломках корабля

**Comment by mrFANRA** [comment]
> > 8й версии нет насоса на старте. Это баг или фича?
> 
> Твердотопливный лежит в обломках корабля

3 раза стартую .. нет его.

**Comment by ExpertLove** [comment]
> 3 раза стартую .. нет его.

Сейчас только запустил - он на месте. Последняя версия с гита

**Comment by mrFANRA** [comment]
> > 3 раза стартую .. нет его.
> 
> Сейчас только запустил - он на месте. Последняя версия с гита

какая версия клиента?

**Comment by ExpertLove** [comment]
Рекомендуемая, как написано в описании к сборке

**Comment by mrFANRA** [comment]
> Рекомендуемая, как написано в описании к сборке

1.1.103 стоит ...

**Comment by ExpertLove** [comment]
Проверяй еще раз, всё работает)

**Comment by SKProCH** [comment]
Возможно причина в мирном режиме, как сказали в чате дискорда. Нужно проверить.

**Comment by ExpertLove** [comment]
Мирный режим? От этого зависит дроп на старте?

**Comment by mrFANRA** [comment]
Но я стартовал без мирного режима.

**Comment by ExpertLove** [comment]
Запустил 3 раза в мирном и обычном режиме
Версия сборки - последний ZIP с гита. Версия игры - Factorio_1.1.107
Насос есть на старте
![Screenshot_6](https://github.com/user-attachments/assets/18596b81-f80c-424e-9a03-8fdc51824310)
